backend:
  name: git-gateway
  branch: main
media_folder: "src/img/media"
public_folder: "/img/media"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/blog"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "projects"
    label: "Projects"
    folder: "src/project"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Project Lead", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

files:
    - name: "home"
      label: "Homepage"
      file: "src/index.md"
      fields:
        - {label: "Body", name: "body", widget: "markdown"}
    - name: "about"
      label: "About page"
      file: "src/about.md"
      fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
